apiVersion: v1
kind: Secret
metadata:
  name: desafio-axia-secrets
  namespace: desafio-axia
type: Opaque
stringData:
  postgres-password: postgres
  postgres-user: postgres
  postgres-db: VeiculosDb

